Information page
Refugees-Say/information_page pull request #10
Opened 2017-12-17 23:06 UTC by Md-Almasri

Hi @eritikass,
I added the header and footer to app file, am I doing right?
Please have a look and let me know if I need to change something before I continue.
thanks

2017-12-18 00:17 UTC, eritikass requested changes
you are in right track for sure - added few comments to to make even better :)

2017-12-18 00:17 UTC, eritikass commented on src/components/Footer.vue
> +  <footer>
this footer element inside footer component is quite strange (same was also in header), and seems also something that can easily result with errors

2017-12-18 00:17 UTC, eritikass commented on src/App.vue
> +  components: { Header, Footer },
write object properties to different lines, this also keep git diff in future when you add/remove something more clean - and better to read anycase

```JavaScript
  components: {
    Footer,
    Header,
  },
```

2017-12-18 00:17 UTC, eritikass commented on src/components/Footer.vue
> +<style scoped>
there seems to be styles that go inside each other, what you think about using [SCSS](http://sass-lang.com/)?

```vue
<style lang="scss" scoped>
footer {
  /* .... */

  .footerLogos {
    /* .... */

    .logo {
      /* .... */
    }
  }
}
</style>
```
you need then also add `sass-loader` and `node-sass`
```bash
yarn add -D sass-loader node-sass
```

2017-12-18 21:44 UTC, Md-Almasri commented on src/components/Footer.vue
> +  <footer>
So should I change footer element into div with footer class name

2017-12-18 22:18 UTC, eritikass commented on src/components/Footer.vue
> +  <footer>
> So should I change footer element into div with footer class name?

i would go with this one

2017-12-19 23:25 UTC, eritikass commented on src/components/Header.vue
> +<style scoped>
this also scss

2017-12-19 23:26 UTC, eritikass commented on package.json
> +    "node-sass": "^4.7.2",
commit also lock `yarn.lock` change

2017-12-21 23:15 UTC, eritikass commented on src/components/AddressAndSupporterInfo.vue
> +        <button class="btn">Show jobs near me</button>
try to use [Internationalization plugin for Vue.js](https://www.npmjs.com/package/vue-i18n) so your site would be easy to translate

2017-12-23 23:07 UTC, Md-Almasri commented
Hi @eritikass ,
Could you please check why personal photo can't be loaded?

2017-12-23 23:32 UTC, eritikass commented
because webpack cant understand that you want to bundle image there - for testing you can try something like that

https://github.com/Refugees-Say/information_page/blob/d006760a4742cc0b43c4e38d7d97cfb3387c462c/src/components/AddressAndSupporterInfo.vue#L25
```diff
-      source: '../assets/img_avatar.png',
+      source: require('../assets/img_avatar.png'),
```

in the end this image i guess should come from url that are located outside this bundle

2017-12-30 13:28 UTC, eritikass commented
@Md-Almasri `LGTM` - i merge if you wish, all other improvments can be made as part of separate pull requests

2018-01-04 18:13 UTC, Md-Almasri commented
Hi @eritikass 
I'll merge it, and make another branch :)

2018-01-04 18:13 UTC, merged